# Site settings
title: "Dwisp's bloggy"
email: dwisp@protonmail.com
description: ""
baseurl: ""
url: "dwisp.github.io"
title_description: "I'm Ivan, a guy who's curios about everything! I graduated Phystech (MIPT) in 2017, getting my Master's in Applied Mathemathics and Physics as well as Bachelor's. My passions are figuring out how things work, generating ideas and traveling around the world."
title_image: "images/misc/hardwired.jpeg"
google_analytics: ""
disqus_account: dwisp
github_repository: https://github.com/dwisp
addthis_id:
post_limit: 8

# Social usernames/URLs
twitter_username:
github_username: dwisp
gitlab_username: dwisp
telegram_username: digitalwisp
instagram_username: 
reddit_username: 
linkedin_link:
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
